class AppStr {
  static String _currentLang = 'en';

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      "goodAfternoon": 'Good Afternoon',
      "goodEvening": 'Good Evening',
      "goodMorning": 'Good Morning',
      "userName": 'Username',
      "income": 'Income',
      "expenses": 'Expenses',
      "transactionHistory": 'Transaction History',
      "seeAll": 'See All',
      "balance": 'Total Balance',
      "expensesMoney": '800.00',
      "transfer": 'Transfer',
      "today": 'Today',
      "topSpending": 'Top Spending',
      "noName": 'No Name',
      "add": 'Add',
      "addTitle": 'Add Title',
      "addAmount": 'Add Amount',
      "category": 'Category Name',
      "explain": 'Explain your transaction',
      "amount": 'Amount',
      "how": 'How',
      "date": 'Date',
      "save": 'Save',
      "isSub": 'Is a Subscription?',
      //Tarjetas
      "nameCard": 'Name Card',
      'numberCard': 'Number Card',
      'bank': 'Bank',
      'isCredit': 'Is a Credit Card?',
      'limit': 'Limit',
      'addCard': 'Save Card',
      'addCardTitle': 'Add Payment',
      'nocards': 'No cards registered.',
      'paymentMethod': 'Payment Method',
      'paymentMethods': 'Payment Methods',
      'choosePaymentMethod': 'Choose Payment Method',
      'noPaymentMethod': 'No payment method',
      'cash': 'Cash',
      'card': 'Card',
      'creditAvailable': 'Credit Available',
      'required': 'Required',
      'fillAllFields': 'Please fill all fields',
      'invalidAmount': 'Invalid amount',
      'areYouSure': 'Are you sure?',
      'delete': 'Delete',
      'statistics': 'Statistics',
      'cancel': 'Cancel',
      'deleteCardMessage': 'Are you sure you want to delete this card?',
      'noNumber': 'No number',
      'enero': 'January',
      'febrero': 'February',
      'marzo': 'March',
      'abril': 'April',
      'mayo': 'May',
      'junio': 'June',
      'julio': 'July',
      'agosto': 'August',
      'septiembre': 'Septembrer',
      'octubre': 'October',
      'noviembre': 'November',
      'diciembre': 'Dicember',
      'chooseDateCut': 'Choose last day of billing cycle: ',
      'dateCut': 'Last day of billing cycle: ',
      'chooseMonth': 'Choose a month',
      'chooseDay': 'Choose a day',
      'select': 'Confirm',
      'chooseDateLimit': 'Choose day of payment deadline: ',
      'dateLimit': 'Day of payment deadline: ',
      'chooseDate': 'Choose Date',
      'noTransactions': 'No transactions yet',
      'settings': 'Settings',
      'language': 'Language',
      'changeUsername': 'Change Username',
      'inputUsername': 'Write your new username',
      'configSavedMessage': 'Configuration saved successfully',
      'settingsLang': 'Language Settings',
      'settingsProfile': 'Profile Settings',
      'For': 'For',
      'month': 'Month',
      'year': 'Year',
      'day': 'Day',
      'week': 'Week',
      'PurchasesButton': 'View Purchases',
      'editar': 'Edit',
      'add_new': 'Add New',
      'name_category': 'Category Name',
      'addCategory': 'Add New Category',
    },
    'es': {
      "goodAfternoon": 'Buenas tardes',
      "goodEvening": 'Buenas noches',
      "goodMorning": 'Buenos días',
      "userName": 'Nombre de usuario',
      "income": 'Ingresos',
      "expenses": 'Gastos',
      "transactionHistory": 'Historial de transacciones',
      "seeAll": 'Ver todo',
      "balance": 'Saldo total',
      "expensesMoney": '800.00', // Este es un número, no se traduce
      "transfer": 'Transferir',
      "today": 'Hoy',
      "topSpending": 'Gastos principales',
      "noName": 'Sin nombre',
      "add": 'Agregar',
      "addTitle": 'Agregar título',
      "addAmount": 'Agregar cantidad',
      "category": 'Nombre de categoría',
      "explain": 'Explica tu transacción',
      "amount": 'Cantidad',
      "how": 'Cómo',
      "date": 'Fecha',
      "save": 'Guardar',
      "isSub": '¿Es una suscripción?',
      // Tarjetas
      "nameCard": 'Nombre en la tarjeta',
      "numberCard": 'Número de tarjeta',
      "bank": 'Banco',
      "isCredit": '¿Es una tarjeta de crédito?',
      "limit": 'Límite',
      "addCard": 'Guardar tarjeta',
      "addCardTitle": 'Agregar método de pago',
      "nocards": 'No hay tarjetas registradas.',
      "paymentMethod": 'Método de pago',
      "paymentMethods": 'Métodos de pago',
      "choosePaymentMethod": 'Elige un método de pago',
      "noPaymentMethod": 'Sin método de pago',
      "cash": 'Efectivo',
      "card": 'Tarjeta',
      "creditAvailable": 'Crédito disponible',
      "required": 'Requerido',
      "fillAllFields": 'Por favor, completa todos los campos',
      "invalidAmount": 'Cantidad inválida',
      "areYouSure": '¿Estás seguro?',
      "delete": 'Eliminar',
      "statistics": 'Estadísticas',
      "cancel": 'Cancelar',
      "deleteCardMessage":
          '¿Estás seguro de que quieres eliminar esta tarjeta?',
      "noNumber": 'Sin número',
      "enero": 'Enero',
      "febrero": 'Febrero',
      "marzo": 'Marzo',
      "abril": 'Abril',
      "mayo": 'Mayo',
      "junio": 'Junio',
      "julio": 'Julio',
      "agosto": 'Agosto',
      "septiembre": 'Septiembre',
      "octubre": 'Octubre',
      "noviembre": 'Noviembre',
      "diciembre": 'Diciembre',
      "chooseDateCut": 'Elige el último día del ciclo de facturación: ',
      "dateCut": 'Último día del ciclo de facturación: ',
      "chooseMonth": 'Elige un mes',
      "chooseDay": 'Elige un día',
      "select": 'Confirmar',
      "chooseDateLimit": 'Elige el día límite de pago: ',
      "dateLimit": 'Día límite de pago: ',
      "chooseDate": 'Elige una fecha',
      "noTransactions": 'Aún no hay transacciones',
      "settings": 'Configuración',
      "language": 'Idioma',
      "changeUsername": 'Cambiar nombre de usuario',
      "inputUsername": 'Escribe tu nuevo nombre de usuario',
      "configSavedMessage": 'Configuración guardada exitosamente',
      "settingsLang": 'Configuración de idioma',
      "settingsProfile": 'Configuración de perfil',
      'For': 'A',
      'month': 'Meses',
      'year': 'Año',
      'day': 'Día',
      'week': 'Semana',
      'PurchasesButton': 'Ver compras',
      'editar': 'Editar',
      'add_new': 'Agregar nueva categoria',
      'name_category': 'Nombre de la categoria',
      'addCategory': 'Agregar nueva categoría',
    },
    'fr': {
      "goodAfternoon": 'Bon après-midi',
      "goodEvening": 'Bonsoir',
      "goodMorning": 'Bonjour',
      "userName": "Nom d'utilisateur",
      "income": 'Revenu',
      "expenses": 'Dépenses',
      "transactionHistory": 'Historique des transactions',
      "seeAll": 'Voir tout',
      "balance": 'Solde total',
      "expensesMoney": '800.00', // Valeur numérique, reste inchangée
      "transfer": 'Transférer',
      "today": "Aujourd'hui",
      "topSpending": 'Dépenses principales',
      "noName": 'Sans nom',
      "add": 'Ajouter',
      "addTitle": 'Ajouter un titre',
      "addAmount": 'Ajouter un montant',
      "category": 'Nom de la catégorie',
      "explain": 'Expliquez votre transaction',
      "amount": 'Montant',
      "how": 'Comment',
      "date": 'Date',
      "save": 'Enregistrer',
      "isSub": 'Est-ce un abonnement ?',

      // Cartes
      "nameCard": 'Nom sur la carte',
      "numberCard": 'Numéro de carte',
      "bank": 'Banque',
      "isCredit": 'Est-ce une carte de crédit ?',
      "limit": 'Limite',
      "addCard": 'Enregistrer la carte',
      "addCardTitle": 'Ajouter un paiement',
      "nocards": 'Aucune carte enregistrée.',
      "paymentMethod": 'Méthode de paiement',
      "paymentMethods": 'Méthodes de paiement',
      "choosePaymentMethod": 'Choisissez une méthode de paiement',
      "noPaymentMethod": 'Aucune méthode de paiement',
      "cash": 'Espèces',
      "card": 'Carte',
      "creditAvailable": 'Crédit disponible',
      "required": 'Requis',
      "fillAllFields": 'Veuillez remplir tous les champs',
      "invalidAmount": 'Montant invalide',
      "areYouSure": 'Êtes-vous sûr ?',
      "delete": 'Supprimer',
      "statistics": 'Statistiques',
      "cancel": 'Annuler',
      "deleteCardMessage": 'Êtes-vous sûr de vouloir supprimer cette carte ?',
      "noNumber": 'Pas de numéro',

      // Mois
      "enero": 'Janvier',
      "febrero": 'Février',
      "marzo": 'Mars',
      "abril": 'Avril',
      "mayo": 'Mai',
      "junio": 'Juin',
      "julio": 'Juillet',
      "agosto": 'Août',
      "septiembre": 'Septembre',
      "octubre": 'Octobre',
      "noviembre": 'Novembre',
      "diciembre": 'Décembre',

      "chooseDateCut": 'Choisissez le dernier jour du cycle de facturation :',
      "dateCut": 'Dernier jour du cycle de facturation :',
      "chooseMonth": 'Choisissez un mois',
      "chooseDay": 'Choisissez un jour',
      "select": 'Confirmer',
      "chooseDateLimit": 'Choisissez la date limite de paiement :',
      "dateLimit": 'Date limite de paiement :',
      "chooseDate": 'Choisissez une date',
      "noTransactions": 'Aucune transaction pour le moment',

      "settings": 'Paramètres',
      "language": 'Langue',
      "changeUsername": "Changer le nom d'utilisateur",
      "inputUsername": 'Entrez votre nouveau nom',
      "configSavedMessage": 'Configuration enregistrée avec succès',
      "settingsLang": 'Paramètres de langue',
      "settingsProfile": 'Paramètres du profil',
      'For': 'Pour',
      'month': 'Mois',
      'year': 'Année',
      'day': 'Jour',
      'week': 'Semaine',
      'PurchasesButton': 'Voir les achats',
      'editar': 'Éditer',
      'add_new': 'Ajouter nouveau',
      'name_category': 'Nom de la catégorie',
      'addCategory': 'Ajouter une nouvelle catégorie',
    },
    'de': {
      "goodAfternoon": 'Guten Nachmittag',
      "goodEvening": 'Guten Abend',
      "goodMorning": 'Guten Morgen',
      "userName": 'Benutzername',
      "income": 'Einnahmen',
      "expenses": 'Ausgaben',
      "transactionHistory": 'Transaktionsverlauf',
      "seeAll": 'Alle anzeigen',
      "balance": 'Gesamtguthaben',
      "expensesMoney": '800.00',
      "transfer": 'Überweisen',
      "today": 'Heute',
      "topSpending": 'Top-Ausgaben',
      "noName": 'Kein Name',
      "add": 'Hinzufügen',
      "addTitle": 'Titel hinzufügen',
      "addAmount": 'Betrag hinzufügen',
      "category": 'Kategoriename',
      "explain": 'Erklären Sie Ihre Transaktion',
      "amount": 'Betrag',
      "how": 'Wie',
      "date": 'Datum',
      "save": 'Speichern',
      "isSub": 'Ist es ein Abonnement?',

      // Karten
      "nameCard": 'Name auf der Karte',
      "numberCard": 'Kartennummer',
      "bank": 'Bank',
      "isCredit": 'Ist es eine Kreditkarte?',
      "limit": 'Limit',
      "addCard": 'Karte speichern',
      "addCardTitle": 'Zahlung hinzufügen',
      "nocards": 'Keine Karten registriert.',
      "paymentMethod": 'Zahlungsmethode',
      "paymentMethods": 'Zahlungsmethoden',
      "choosePaymentMethod": 'Zahlungsmethode wählen',
      "noPaymentMethod": 'Keine Zahlungsmethode',
      "cash": 'Bar',
      "card": 'Karte',
      "creditAvailable": 'Verfügbarer Kredit',
      "required": 'Erforderlich',
      "fillAllFields": 'Bitte alle Felder ausfüllen',
      "invalidAmount": 'Ungültiger Betrag',
      "areYouSure": 'Sind Sie sicher?',
      "delete": 'Löschen',
      "statistics": 'Statistiken',
      "cancel": 'Abbrechen',
      "deleteCardMessage": 'Möchten Sie diese Karte wirklich löschen?',
      "noNumber": 'Keine Nummer',

      // Monate
      "enero": 'Januar',
      "febrero": 'Februar',
      "marzo": 'März',
      "abril": 'April',
      "mayo": 'Mai',
      "junio": 'Juni',
      "julio": 'Juli',
      "agosto": 'August',
      "septiembre": 'September',
      "octubre": 'Oktober',
      "noviembre": 'November',
      "diciembre": 'Dezember',

      "chooseDateCut": 'Wählen Sie den letzten Tag des Abrechnungszeitraums:',
      "dateCut": 'Letzter Tag des Abrechnungszeitraums:',
      "chooseMonth": 'Monat wählen',
      "chooseDay": 'Tag wählen',
      "select": 'Bestätigen',
      "chooseDateLimit": 'Wählen Sie den Zahlungstermin:',
      "dateLimit": 'Zahlungstermin:',
      "chooseDate": 'Datum wählen',
      "noTransactions": 'Noch keine Transaktionen',

      "settings": 'Einstellungen',
      "language": 'Sprache',
      "changeUsername": 'Benutzernamen ändern',
      "inputUsername": 'Neuen Benutzernamen eingeben',
      "configSavedMessage": 'Einstellungen erfolgreich gespeichert',
      "settingsLang": 'Spracheinstellungen',
      "settingsProfile": 'Profileinstellungen',
      'For': 'Für',
      'month': 'Monate',
      'year': 'Jahr',
      'day': 'Tag',
      'week': 'Woche',
      'PurchasesButton': 'Einkäufe anzeigen',
      'editar': 'Bearbeiten',
      'add_new': 'Neu hinzufügen',
      'name_category': 'Kategoriename',
      'addCategory': 'Neue Kategorie hinzufügen',
    },
  };

  static void setLang(String lang) {
    _currentLang = _getLangCode(lang);
  }

  static String _getLangCode(String name) {
    switch (name) {
      case 'Español':
        return 'es';
      case 'English':
        return 'en';
      case 'Français':
        return 'fr';
      case 'Deutsch':
        return 'de';
      default:
        return 'en';
    }
  }

  static String get(String key) {
    return _localizedValues[_currentLang]![key] ?? key;
  }
}
